# Generated by Django 2.1.1 on 2018-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laochragael', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('club_county', models.CharField(max_length=50)),
                ('club_colours', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
