# Generated by Django 2.1.1 on 2018-11-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laochragael', '0002_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
