# Generated by Django 2.1.1 on 2018-11-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laochragael', '0005_auto_20181114_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
