# Generated by Django 2.1.1 on 2018-11-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laochragael', '0011_auto_20181114_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
